### ISSUE TITLE
Fix bdd capacity test to complete on Macos

### ISSUE THREAD

**Issue by blewater** [e-money/em-ledger#106]
**Describe the bug**
Observed at SDK 0.42.6, 0.42.7
On MacOs the capacity test does not complete the roundabout evoking of 400 events and subsequent reception. 

**How to reproduce**
```shell
go test -mod=readonly -v --tags="bdd" bdd_test.go capacity_test.go
```

**Expected behavior**
bdd test pass--meaning all generated 400 events sent and received.

**Screenshots or log output**
Instead, 348-389 are received.

**Additional context**
While this appears to require a simple timing adjustment, it may require overhauling the event handler that replaced the simple event dispatch/reception mechanism.

**Comment by haasted** [comment]
The test has lately been even more unreliable for me locally, sometimes only registering 1 succesful transaction. I'll investigate to find out whether there is a more fundamental issue at hand.

**Comment by haasted** [comment]
The issue was that transactions were queried too quickly, and considered "failed" if they had not yet been included in a block.

I modified the test to re-query transaction ids that fail, which makes it successful.
