### ISSUE TITLE
emd cli vesting listed twice

### ISSUE THREAD

**Issue by blewater** [e-money/em-ledger#110]
**Describe the bug**
emd q
  evidence            Evidence transaction subcommands
  gov                 Governance transactions subcommands
  ibc                 IBC transaction subcommands
  ibc-transfer        IBC fungible token transfer transaction subcommands
  issuer              Control inflation rates and manage liquidity providers
  liquidityprovider   Liquidity provider operations
  market              Market transaction commands
  multisign           Generate multisig signatures for transactions generated offline
  sign                Sign a transaction generated offline
  sign-batch          Sign transaction batch files
  slashing            Slashing transaction subcommands
  staking             Staking transaction subcommands
  validate-signatures Validate transactions signatures
**vesting             Vesting transaction subcommand**
**vesting             Vesting transaction subcommand**

**How to reproduce**
1. make build
2. emd q or tx

**Comment by haasted** [comment]
Removed duplicate "tx vesting" entries. The "q vesting" entries appear to have been removed at some earlier point.
