### ISSUE TITLE
go testing the authority keeper takes a long time to complete

### ISSUE THREAD

**Issue by blewater** [e-money/em-ledger#113]
**Is your feature request related to a problem? Please describe.**
This is a subjective relative assessment but the authority keeper tests take the most time to complete compared to the others.

**Describe the solution you'd like**
Removing testing redundancies in the keeper tests without compromising the present quality guarantees.

**Additional context**
Likely a test was introduced during the `rotate authority key` work  #95.

**Comment by haasted** [comment]
Invoking `go clean -testcache` and running the tests reveals a running time of 44s for the `github.com/e-money/em-ledger/x/authority/client/cli` package, so the assessment seems correct. Investigating.

**Comment by blewater** [comment]
Addressed in https://github.com/e-money/em-ledger/commit/8fcc9937030755e8662a7d67afa2ec25354c11a8
