### ISSUE TITLE
timeout_commit seems to default to 5 sec

### ISSUE THREAD

**Issue by mdyring** [e-money/em-ledger#114]
**Describe the bug**
Previous behaviour was to hardcode timeout_commit to 60 seconds and ignore config.toml.

We should revert to this, or alternatively, let the default value be 60 seconds instead of 5. 

**How to reproduce**
Spin up testnet based on develop branch.

**Comment by haasted** [comment]
The consensus settings have now been fixed, however a new issue has been unearthed.

The `staking` module now keeps historical entries of the validator set. These are updated for every block, causing the app_state to be continually updated and a new block to be immediately created. Our dynamic blocktime essentially creates a cascade of blocks in this scenario.

Working on a fix for this.

**Comment by haasted** [comment]
Fixed.
