### ISSUE TITLE
Using halt-height makes it impossible get back to consensus

### ISSUE THREAD

**Issue by haasted** [e-money/em-ledger#12]
**Describe the bug**
When starting `emd` with the `--halt-height` flag, the node cannot later continue participating in consensus. 

Killing the node with ctrl+c does not yield this problem.

**How to reproduce**
1. Start full node with seeds and add the flag `--halt-height 100`. 
2. The node will synchronize and shut down at block 100.
3. Start the node again without a halt height.
4. The node will stop and display the error message `panic: state.AppHash does not match AppHash after replay. `

**Expected behavior**
The node should continue synchronizing from block 100.

**Comment by mdyring** [comment]
Fixed in v0.6.6
