### ISSUE TITLE
API Endpoint 

### ISSUE THREAD

**Issue by JDinesenEmoney** [e-money/em-ledger#120]
**Describe the bug**
new API endpoint for returning delegations, does not work. Call to new endpoint results in an error being thrown:

_rpc error: code = NotFound desc = unable to find delegations for address emoney1dhdlcrqdk0ze9n22my5e0ttyayc2zxgv42vmzq: key not found_

Should return array of delegations - empty if thats the case, but no errors

OLD endpoint:
staking/delegators/${address}/delegations

NEW endpoint:
cosmos/staking/v1beta1/delegations/${address}

Examples:
OLD: 
https://lilmermaid.validator.network/api/staking/delegators/emoney1dhdlcrqdk0ze9n22my5e0ttyayc2zxgv42vmzq/delegations

NEW:
https://lilmermaid.validator.network/api/cosmos/staking/v1beta1/delegations/emoney1dhdlcrqdk0ze9n22my5e0ttyayc2zxgv42vmzq

**Comment by blewater** [comment]
Not a helpful error message, but the API is active. That's the error for a non-delegator address :)
Steps for a positive response:
1. Query validators https://lilmermaid.validator.network/api/cosmos/staking/v1beta1/validators
2. Find a delegator for a validator https://lilmermaid.validator.network/api/cosmos/staking/v1beta1/validators/emoneyvaloper1aw569wk7mhh45z8ecjur5w6q0rkcsk52p3wsh3/delegations
3. Query for an existing delegator and it would return a positive response :) https://lilmermaid.validator.network/api/cosmos/staking/v1beta1/delegations/emoney1pll24pshee8se7mfn5v0772k6emw0dweg7rwmh

```json
{
  "delegation_responses": [
    {"delegation":{"delegator_address":"emoney1pll24pshee8se7mfn5v0772k6emw0dweg7rwmh","validator_address":"emoneyvaloper1aw569wk7mhh45z8ecjur5w6q0rkcsk52p3wsh3","shares":"0.340139173940505155"},"balance":{"denom":"ungm","amount":"0"}}
  ],
  "pagination": {
    "next_key": null,
    "total": "1"
  }
}
```

**Comment by blewater** [comment]
@JDinesenEmoney I'm going ahead and closing this as there is not much else to do on our end and we may continue at the Cosmos side.
