### ISSUE TITLE
Access to types in `x/inflation/internal/types`

### ISSUE THREAD

**Issue by ryuash** [e-money/em-ledger#136]
**Is your feature request related to a problem? Please describe.**
We are trying to parse the inflation module for big dipper 2.0 and would like access to `x/inflation/internal/types`. 
It's currently not possible for us to access `types` as it is inside the `internal` folder.

**Describe the solution you'd like**
Move `x/inflation/internal/types` to `x/inflation/types`.
Or remove the internal folder altogether as It's simply not the best practice of building Cosmos modules anymore since `Cosmos v0.40`

**Comment by blewater** [comment]
@ryuash, we removed the internal designation in the master branch [136-inflation](https://github.com/e-money/em-ledger/tree/136-inflation). Let me know whether it meets your needs or need anything else.

**Comment by ryuash** [comment]
This is perfect, thank you!

**Comment by haasted** [comment]
Sounds good. We'll put this on the next minor-version release.
