### ISSUE TITLE
The upgrade test and docker image broke

### ISSUE THREAD

**Issue by blewater** [e-money/em-ledger#138]
**Describe the bug**
The upgrade bdd test broke and the **test** upgrade docker image build do not complete.

**How to reproduce**
1. make build-docker
2. go test -v --tags="bdd" bdd_test.go upgrade_test.go

**Expected behavior**
Both steps succeed.

**Screenshots or log output**
executor failed running [/bin/sh -c go install github.com/cosmos/cosmos-sdk/cosmovisor/cmd/cosmovisor@latest]: exit code: 1

**Comment by haasted** [comment]
Fixed.
