### ISSUE TITLE
Roll new release with Tendermint v0.34.13

### ISSUE THREAD

**Issue by mdyring** [e-money/em-ledger#143]
This release should fix the ABCIQuery locking issue observed when running a IBC relayer:

https://github.com/tendermint/tendermint/blob/v0.34.13/CHANGELOG.md

**Comment by haasted** [comment]
Upgraded the dependency in 47cb3a7235d7fd8a6d951c5d21b77c8e74c20bbf and synced the mainnet without issue. Looks like it can go into the next minor release.

**Comment by haasted** [comment]
Released in v1.1.2.
