### ISSUE TITLE
Failed transfer is reported as succesful by light client interface

### ISSUE THREAD

**Issue by haasted** [e-money/em-ledger#18]
**Describe the bug**
Transfer that fails due to being a restricted denomination, is reported as succesful.

**How to reproduce**
The failed transfer at https://e-money.network/transactions/38CEF4E9AFB7FFC3113ED146465A7F5208174B2D4A483E2F3BE22ECDDEE0BA15

is reported as succesful by the light client interface:
http://emoney.validator.network/light/txs/F2C3698A886B96ED48A8CBBB3452CD5035B51BBC7E3BF86662A00AE4A2CFB4AF

**Comment by mdyring** [comment]
These are different transactions. Works as expected (success=false):

http://emoney.validator.network/light/txs/38CEF4E9AFB7FFC3113ED146465A7F5208174B2D4A483E2F3BE22ECDDEE0BA15
