### ISSUE TITLE
Adding the IBC ante handler filtering out redundant packets to save fees

### ISSUE THREAD

**Issue by blewater** [e-money/em-ledger#183]
**Is your feature request related to a problem? Please describe.**
Add the 42.x IBC redundant ante handler https://github.com/cosmos/cosmos-sdk/pull/10211 like other chains.

**Describe the solution you'd like**
Branched against master.

**Additional context**
As described in the linked PR, it is a backport of ibc-go feature to the 42.x trunk which embeds ibc.

**Comment by haasted** [comment]
Stability of the PR was confirmed by Notional.
