### ISSUE TITLE
Querying account with EMD doesn't show any balance

### ISSUE THREAD

**Issue by artemisone-org** [e-money/em-ledger#188]
**Describe the bug**
emd output seems to be limited at the moment as someone that has used a similar implementation I would expect the account to show the balance along with the tokens being held

**How to reproduce**

Just query with `emd query account <emoney-addr>`

**Expected behavior**
Expecting similar behavior as KVCLI
![image](https://user-images.githubusercontent.com/95833113/145329791-d21e8c3a-015d-4e73-8e43-28cd2058e5a8.png)

**Comment by blewater** [comment]
Thanks, @artemisone-org for opening an issue with us! 
Since the Cosmos SDK upgrade to 0.40+ (aka Stargate) the upgraded chains reply balances through the bank module
`emd bank balances <addr>`
[sdk reference](https://docs.cosmos.network/master/modules/bank/06_client.html#balances)

e.g.
```shell
emd q bank balances emoney1gjudpa...
{"balances":[{"denom":"echf","amount":"100000000000"},{"denom":"edkk","amount":"3500000000000"},{"denom":"eeur","amount":"100000000000"},{"denom":"ejpy","amount":"3500000000000"},{"denom":"enok","amount":"3500000000000"},{"denom":"esek","amount":"3500000000000"},{"denom":"ungm","amount":"990000000000"}],"pagination":{"next_key":null,"total":"0"}}
```

**Comment by artemisone-org** [comment]
Ah it got moved, works for me. Thanks :)
