### ISSUE TITLE
Add information to instruments output

### ISSUE THREAD

**Issue by mdyring** [e-money/em-ledger#33]
It would be great to add some additional information in the instruments query:
https://emoney.validator.network/light/market/instruments
 
```
{
  "height": "82308",
  "result": {
    "instruments": [
      {
        "source": "eeur",
        "destination": "ungm",
        "last_price": "1.538399692959211348",
        "last_traded": "2020-11-04T18:12:40.400949361Z"
      },
      {
        "source": "ungm",
        "destination": "eeur",
        "last_price": "0.650026130775179302",
        "last_traded": "2020-11-04T18:12:40.400949361Z"
      }
    ]
  }
}
```

We should add a "best_price" value that is price returned by invoking createExecutionPlan.

**Comment by mdyring** [comment]
Actually, since the createExecutionPlan uses synthetic orders it would make sense for the instrument output to use to take this into account.

So instruments should return a <denoms> x <denoms> matrix (minus identical denoms), call the createExecutionPlan for each to get the best price as above.

Information on last_price and last_traded should be fetched the way it is today (from instruments that have traded).

For now let's avoid introducing any caching mechanism for this, but I imagine it would be useful at some point.. Either at the query level or perhaps inside createExecutionPlan.

**Comment by blewater** [comment]
Test Results: for test orders (below) with 4 instruments (eur, usd, jpy, chf) are generated (4*(4-1))  = 12 pairs
[
   {
      "source":"chf",
      "destination":"eur",
      "best_price":"9223372036854775807.000000000000000000"
   },
   {
      "source":"chf",
      "destination":"jpy",
      "best_price":"9223372036854775807.000000000000000000"
   },
   {
      "source":"chf",
      "destination":"usd",
      "best_price":"0.230769230769230770",
      "last_price":"4.333333333333333333",
      "last_traded":"2020-12-07T13:13:59.232734Z"
   },
   {
      "source":"eur",
      "destination":"chf",
      "best_price":"9223372036854775807.000000000000000000"
   },
   {
      "source":"eur",
      "destination":"jpy",
      "best_price":"0.059356966199505360"
   },
   {
      "source":"eur",
      "destination":"usd",
      "best_price":"0.833333333333333334"
   },
   {
      "source":"jpy",
      "destination":"chf",
      "best_price":"9223372036854775807.000000000000000000"
   },
   {
      "source":"jpy",
      "destination":"eur",
      "best_price":"9223372036854775807.000000000000000000"
   },
   {
      "source":"jpy",
      "destination":"usd",
      "best_price":"9223372036854775807.000000000000000000"
   },
   {
      "source":"usd",
      "destination":"chf",
      "best_price":"9223372036854775807.000000000000000000",
      "last_price":"0.230769230769230769",
      "last_traded":"2020-12-07T13:13:59.232734Z"
   },
   {
      "source":"usd",
      "destination":"eur",
      "best_price":"9223372036854775807.000000000000000000"
   },
   {
      "source":"usd",
      "destination":"jpy",
      "best_price":"9223372036854775807.000000000000000000"
   }
]
```
	o := order(acc1, "100eur", "120usd")
	o = order(acc1, "72eur", "1213jpy")
	o = order(acc1, "72chf", "312usd")
	o = order(acc2, "156usd", "36chf")
```

**Comment by blewater** [comment]
### Question: shouldn't the best price be reversed in the following:
{
"source":"chf",
"destination":"usd",
"best_price":"0.230769230769230770",
"last_price":"4.333333333333333333",
"last_traded":"2020-12-07T13:13:59.232734Z"
}

**Comment by blewater** [comment]
### Question: should we remove the best price when the maxInt value is returned?
{
"source":"jpy",
"destination":"chf",
"best_price":"9223372036854775807.000000000000000000"
}

**Comment by blewater** [comment]
Question: Improve executePlan? After the following 2 orders 

1. 100eur -> 120usd (**4.333**)
2. 156usd -> 36chf.  (**0.833**)

the best price for eur -> chf could be **3.611**

Instead, we present maxInt:
{
"source":"eur",
"destination":"chf",
"best_price":"9223372036854775807.000000000000000000"
}
