### ISSUE TITLE
Collected transaction fees should be sent to buyback module

### ISSUE THREAD

**Issue by mdyring** [e-money/em-ledger#41]
**Is your feature request related to a problem? Please describe.**
Collected transaction fees are distributed as staking rewards, leading to very small amounts (almost "dust")  of stablecoins being distributed.

There are also some potential regulatory issues with distributing transaction fees like this.

**Describe the solution you'd like**
Similar to stablecoin inflation, transaction fees should be sent to the buyback module instead of being distributed. 

**Describe alternatives you've considered**
Burning of collected fee tokens. While it could make sense for stablecoins (reducing circulating supply), this would be foolish if external tokens (such as ATOMs) were accepted as fees later on.

**Comment by blewater** [comment]
I'm sure there is a back-analysis in your thinking, but why not always collect the fees in the staking token? I think the concept of charging stable-coin fees is unprecedented--(functioning as gas too) and reduces the importance of NGM function as a utility token. I could see the increasing complexity of stablecoins economics etc.
