### ISSUE TITLE
Avoid validator jailing on chain halts

### ISSUE THREAD

**Issue by mdyring** [e-money/em-ledger#52]
**Describe the bug**
After a multi-hour chain halt, any validator who is not signing the first block at recovery will be jailed. This is undesirable as many of these might be trying to recover and will now have to wait for the minimum jailing duration.

**Expected behavior**
Open for discussion. But:

* If there is more than (say) 1H between two blocks, it could make sense to reset the "missed block" state.
* Consider lowering minimum jailing duration as well.

**Comment by mdyring** [comment]
@haasted I suggest we close this issue and instead:
1. Integrated #27 to ensure coordinated and fast upgrades
2. Increase `downtime_jail_duration` to 24H. This also addresses the complaint from many validators that 1H is not enough to recover a validator.

**Comment by haasted** [comment]
Both suggestions were addressed with the emoney-3 upgrade.
